[package]
name = "docker_container_test"
version = "0.1.0"
edition = "2021"

[dependencies]
uiautomation = { path = "../../crates/uiautomation", features = ["remote_operations", "process"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] } 